feat: Adjusted the hitbox coordinates of where the stones should be dropped (FM-266).
curiouslearning/FeedTheMonsterJS pull request #1411
Opened 2024-11-06 14:47 UTC by bernhardccodev

# Changes
- Moved the handling if the stones dropped on the correct coordinates from gameplay-scene.ts to monster.ts.

# How to test
- Run locally, then start the game.
- Select any level and during the gameplay, dropping of stones should be withing or very close to the monster's face.
- Repeat this process on different screen sizes.

Ref: [FM-266](https://curiouslearning.atlassian.net/browse/FM-266)

[FM-266]: https://curiouslearning.atlassian.net/browse/FM-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-06 15:12 UTC, woodsjohn-codev approved these changes
looks good to me

2024-11-06 15:12 UTC, miguelccodev requested changes

2024-11-06 15:12 UTC, miguelccodev commented on src/components/monster.ts
> +    const isWithinHitboxX = x <= (monsterXCenter + rangeFactorX) && x >= (monsterXCenter - rangeFactorX);
As a perf improvement,

`(monsterYCenter + rangeFactoryY) && y >= (monsterYCenter - rangeFactoryY);` and  `(monsterXCenter + rangeFactorX) && x >= (monsterXCenter - rangeFactorX);` can be calculated on instantiation.

The app has a reinitialize logic when screen resizes so we only need to determine those once and just compare x and y respectively.

2024-11-06 15:29 UTC, miguelccodev approved these changes
Looks good!

2024-11-07 03:54 UTC, ashwinnair-chimple commented on src/components/monster.ts
> +    const rangeFactoryY = 50; //SUBCTRACT FROM CENTER TO TOP, ADD FROM CENTER TO BOTTOM.
Small correction with naming rangeFactor instead of rangeFactory

2024-11-07 03:55 UTC, ashwinnair-chimple commented on src/components/monster.ts
> +    this.hitboxRangeY.from = monsterCenterY - rangeFactoryY;
Small correction with naming rangeFactorY instead of rangeFactoryY

2024-11-07 03:58 UTC, ashwinnair-chimple commented on src/components/monster.ts
> +    this.hitboxRangeY.to = monsterCenterY + rangeFactorX;
Shouldn't this line of code be 
this.hitboxRangeY.to = monsterCenterY + **rangeFactorY**; instead of **X**

2024-11-07 03:59 UTC, ashwinnair-chimple reviewed
added few comments

2024-11-07 06:49 UTC, ashwinnair-chimple approved these changes
Approved

2024-11-07 06:49 UTC, merged