feat: Updated Start Scene from canvas implementation to HTML.
curiouslearning/FeedTheMonsterJS pull request #1456
Opened 2024-12-09 05:14 UTC by bernhardccodev

# Changes
- Replaced the start scene background from Canvas to HTML implementation.
- Updated Timer component creation, originally using a background class, now points to the ID background. So it won't bug out due to the implementation of Start Scene HTML background.
- Updated base button component by adding a _destroy method.
- Added test cases for background component and updated test case of base button by adding the destroy test scenario.

# How to test
- Run FTM app on browser.
- In start scene, press F12 to check if the rendered Play Button and Background are HTML implementation by viewing them on the DOM tree.
- Press Play and select any game level.
- In the game level, there should be a timer rendered.

Ref: [FM-288](https://curiouslearning.atlassian.net/browse/FM-288)

2024-12-09 09:51 UTC, woodsjohn-codev approved these changes

2024-12-09 10:39 UTC, miguelccodev requested changes
Added comments.

2024-12-09 10:39 UTC, miguelccodev commented on src/components/buttons/base-button-component/base-button-component.ts
> +  public _destroy() {
rename to `destroy()`.

Let's keep this consistent, eventually all html components will extend the base html one.

2024-12-09 10:39 UTC, miguelccodev commented on src/scenes/start-scene.ts
> +  private logTappedStartFirebaseEvent() {
Add a unit test that expects `sendTappedStartEvent` to have been called.

2024-12-09 11:25 UTC, ashwinnair-chimple commented on src/components/buttons/play-button/play-button.scss
> +
remove all the unused media queries to keep the code clean

2024-12-09 11:25 UTC, ashwinnair-chimple commented on src/components/buttons/play-button/play-button.scss
> +      right: 50%;
Only left: 50% is needed when using transform: translate(-50%, -50%)
right: 50% can be remobed

2024-12-09 11:34 UTC, ashwinnair-chimple reviewed
added comments

2024-12-09 15:31 UTC, miguelccodev approved these changes

2024-12-10 04:18 UTC, ashwinnair-chimple approved these changes
Approved

2024-12-10 04:18 UTC, merged